schema_version: 1

context:
  name: azure-mgmt-maps
  version: 2.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-maps-${{ version }}.zip
  sha256: 384e17f76a68b700a4f988478945c3a9721711c0400725afdfcb63cf84e85f0e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.2.0,<2.0
    - msrest >=0.6.21

tests:
  - python:
      imports:
        - azure.mgmt.maps
        - azure.mgmt.maps.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Maps Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
